### ISSUE TITLE
Floating .Fab layers?

### ISSUE THREAD

**Issue by mr-september** [Bastardkb/Elite-C-holder#3]
Seeing this on KiCAD:

![image](https://user-images.githubusercontent.com/45350177/165009724-fceaf5d0-08a0-44c2-9610-e549fd04127c.png)

Is this anything to be concerned about?

**Comment by mr-september** [comment]
bump?

**Comment by bstiq** [comment]
Hi, oops missed that.
Can be safely ignored, just old adapter edge cuts for reference.
