### ISSUE TITLE
What does the handedness resistor actually do?

### ISSUE THREAD

**Issue by Max585t** [Bastardkb/Elite-C-holder#5]
Im making a version of the Elite-C holder that uses RJ9 jacks instead of 3.5mm jacks. With this change, Im changing the halves to communicate with i2c rather than serial. Im not sure if I need to keep the handedness resistor or not

**Comment by bstiq** [comment]
Hello,

The handedness resistor is optional, and will pull a pin to GND on one side, to VCC on the other side.
This is not supported in the default firmware, you will need to enable the appropriate option and recompile it.
